services:

  api:
    build:
      context: ./Weather # Path to the folder containing the Dockerfile for the API
      dockerfile: Dockerfile # The Dockerfile name in the Weather folder
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=db
      - DB_PORT=3306
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:latest
    environment:
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 15s
      timeout: 30s
      retries: 5

  frontend:
    build:
      context: ./frontend # Path to the frontend folder containing Dockerfile-front
      dockerfile: Dockerfile-front # Specify the custom Dockerfile name
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "80:5173"
    depends_on:
      - api